name: Python Flask CI

on:
  push:
    branches: [ master ]  # Runs when you push to master
  workflow_dispatch:       # Also allows manual run from GitHub

jobs:
  build:
    runs-on: self-hosted  # Runs on your self-hosted runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3


    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: |
        cd /home/ec2-user/actions-runner/_work/prize-bonds-app/prize-bonds-app
        nohup gunicorn -w 4 -b 0.0.0.0:5002 serials_db:app > app.log 2>&1 &

